import { NextResponse } from "next/server";

// DEPRECATED — pairing codes are now generated by the desktop app via POST /api/pairing/request
export async function POST() {
  return NextResponse.json(
    { error: "Este endpoint foi descontinuado. Use o QR code no app KidsPC." },
    { status: 410 }
  );
}
